### ISSUE TITLE
LSPClient not found

### ISSUE THREAD

**Issue by jbromberg** [ChimeHQ/LanguageClient#14]
Just a heads up when installing this package Xcode gives the following error: `product 'LSPClient' required by package 'languageclient' target 'LanguageClient' not found in package 'LanguageServerProtocol'.`

Looks like LSPClient was removed from LanguageServerProtocol.

**Comment by mattmassicotte** [comment]
Wow, did this ever go badly. There was indeed a major change a while ago that messed things up. And someone tried to fix it https://github.com/ChimeHQ/LanguageClient/pull/12. But I dropped the ball on it.

**Comment by mattmassicotte** [comment]
Addressed with https://github.com/ChimeHQ/LanguageClient/releases/tag/0.7.1
