### ISSUE TITLE
No such module 'AnyCodable' in 0.3.0

### ISSUE THREAD

**Issue by intitni** [ChimeHQ/LanguageClient#2]
Hi,

Just trying out this package. But Xcode complains that there is no module called `AnyCodable`. I noticed that the last commit says it removed `AnyCodable` and replaced it with `LSPAny`, but at the top of the files, `AnyCodable` is still imported. Should they be removed?

**Comment by mattmassicotte** [comment]
Yes they definitely should and thank you for reporting this. Kind of unclear how this mistake got pass me. Now fixed on main and I'll be making a new release in a moment.
