### ISSUE TITLE
Ignored completion handler in InitializingServer

### ISSUE THREAD

**Issue by mchakravarty** [ChimeHQ/LanguageClient#6]
I noticed a problem with `setHandlers(:completionHandler:)` in the `InitilizingServer`. The implementation of [that function](https://github.com/ChimeHQ/LanguageClient/blob/8731343dc6f2bbfd7d10b5491e0e49a1ae76b96c/Sources/LanguageClient/InitializingServer.swift#L110) ignores its `completionHandler` argument. As a consequence, if you attempt to use the `async await` variant of `setHandlers()`, the Swift runtime complains by reporting 

> SWIFT TASK CONTINUATION MISUSE: setHandlers(_:) leaked its continuation!

(I worked around this by setting the handlers in the configuration, but thought the issue is still worth reporting.)

**Comment by mattmassicotte** [comment]
Wow thank you so much for this report, it was definitely worth it! Should be fixed with 28cebbf.

**Comment by mchakravarty** [comment]
Great — thanks!
